### ISSUE TITLE
Crash on printing demangled name

### ISSUE THREAD

**Issue by kkolakowski** [mattgallagher/CwlDemangle#2]
Hello

We are using your demangle swift code in our project to print stack traces in a little bit more readable way. 

Unfortunately this mangled name is crashing `Demangle.swift`on printing its name, after calling `SwiftName.description` with following string passed to `demangleSwiftName` to create `SwiftName` instance in the first place: 

`_TFFFFC9Le_Figaro11DataManagerP33_4BF0F705F2DC93973E68326EF6A0FFBA16getSingleArticleFTGSqSS_13articleSourceGSqSS_10articleUrlGSqSS_17completionHandlerGSqFT_T__12errorHandlerGSqFGSqPs5Error__T___T_U_FGSqP__T_U_FCSo22NSManagedObjectContextT_U_FT6resultGSqP__5errorGSqPS1____T_`

as string parameter. 

Swift 3.0, Xcode 8.0

**Comment by mattgallagher** [comment]
I'm not able to reproduce your problem. The following code:

```
do {
    let result = try demangleSwiftName("_TFFFFC9Le_Figaro11DataManagerP33_4BF0F705F2DC93973E68326EF6A0FFBA16getSingleArticleFTGSqSS_13articleSourceGSqSS_10articleUrlGSqSS_17completionHandlerGSqFT_T__12errorHandlerGSqFGSqPs5Error__T___T_U_FGSqP__T_U_FCSo22NSManagedObjectContextT_U_FT6resultGSqP__5errorGSqPS1____T_").description
    print(result)
}

```

Completes without problem, printing the result:

`Le_Figaro.DataManager.((getSingleArticle in _4BF0F705F2DC93973E68326EF6A0FFBA) (Swift.String?, articleSource : Swift.String?, articleUrl : Swift.String?, completionHandler : () -> ()?, errorHandler : (Swift.Error?) -> ()?) -> ()).(closure #1).(closure #1).(closure #1)`

I tested -Onone, -O and -O -whole-module-optimization.

If you're able to give me a main.swift file that crashes or a crash log showing where it crashes, then I can do more. Otherwise my suggestion is... do you have the latest version of CwlDemangle.swift? Have you tried cleaning your project and rebuilding? Are you loading the name from a custom buffer that is causing problems?

**Comment by kkolakowski** [comment]
Helo Matt, sorry for a long response time.

Sorry that I haven't provided a minimalistic case when this occur out of my laziness, I was sure it will crash elsewhere too.

I tested this case a little bit more and things are getting stranger. It seems that crash occurs only in a specific place in code, even with the same string as argument. Since I wasn't able to reproduce it in a standalone project I will keep my eye on it and let you know if I find anything specific. 

Thanks for your work, you can consider this issue as closed.
